config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations'}
  # get 'pages/home'
  root 'pages#home'
  resources :todo_lists do
    resources :todo_items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  scope :completed, -> { where(completed: true) }
end

app/models/todo_list.rb
class TodoList < ApplicationRecord

  validates :title, presence: true

  has_many :todo_items
  belongs_to :user

  
  def percent_completed
    return 0 if total_items == 0
    (100 * completed_items.to_f / total_items).round
  end
  
  def completed_items
    @completed_items ||= todo_items.completed.count
  end

  def total_items
    @total_items ||= todo_items.count
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @todo_list ||= TodoList.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def sign_up_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :email)
  end

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET todo_lists/1/todo_items
  def index
    @todo_items = @todo_list.todo_items
  end

  # GET todo_lists/1/todo_items/1
  def show
  end

  # GET todo_lists/1/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.build
  end

  # GET todo_lists/1/todo_items/1/edit
  def edit
  end

  # POST todo_lists/1/todo_items
  def create
    @todo_item = @todo_list.todo_items.build(todo_item_params)

    if @todo_item.save
      redirect_to(@todo_item.todo_list)
    else
      render action: 'new'
    end
  end

  # PUT todo_lists/1/todo_items/1
  def update
    if @todo_item.update_attributes(todo_item_params)
      redirect_to([@todo_item.todo_list, @todo_item], notice: 'Todo item was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE todo_lists/1/todo_items/1
  def destroy
    @todo_item.destroy

    redirect_to todo_list_todo_items_url(@todo_list)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_item_params
      params.require(:todo_item).permit(:description, :completed, :completed_at, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_item = TodoItem.new
  end

  # GET /todo_lists/new
  def new
    @todo_list ||= TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)


    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to root_path, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { redirect_to root_path }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def my_todo(todos)
    todos.each do |item|
      concat content_tag(:li, (link_to "#{item.title}", todo_list_path(item.id), class: 'nav-link text-dark text-center'), class: 'list-group-item')
    end

  end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/_navigation.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'And What i do?', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
      <% if user_signed_in? %>
        <p class='text-muted'>
          Welcome <%= current_user.name %>
        </p>
        <p class='text-muted'>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'text-muted nav-link' %>
        </p>
      <% else %>
        <p class='text-muted'>
        <%= link_to 'Sign in', new_user_session_path, class: 'text-muted nav-link' %>
        </p>
        <p class='text-muted'>
          <%= link_to 'Sign up', new_user_registration_path, class: 'text-muted nav-link' %>
        </p>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>And what I do?</title>
    <meta name="description" content="And what I do?" />
    <meta name="title" property="og:title" content="Todo app" />
    <meta property="og:type" content="Website" />
    <meta name="image" property="og:image" content="https://i.imgur.com/ZD9Zy77.png">
    <meta name="description" property="og:description" content="Todo app" /><meta name="author" content="Ricardo Montengro" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <div class='container mt-5'>
    <div class="row d-flex justify-content-center">
      <div class="col-5">
        <div class="text-center mb-5">
          <h1>What you need to do!</h1>
        </div>

        <%= render 'todo_lists/form', todo_list: @todo_list  %>

        <div class="card">
          <ul class="list-group list-group-flush">
            <% my_todo(current_user.todo_lists) %>
          </ul>
        </div>
      </div>
    </div>

  </div>
<% else %>
  <div class='container mt-5'>
    <div class="row d-flex justify-content-center">
			<div class="col-3 h-100">
				<div class="text-center mb-5">
        </div>
			</div>
      
      <div class="col-5">
        <div class="text-center mb-5">
          <h1>What you need to do?</h1>
        </div>

      </div>

      <div class="col-3 h-100">
        <div class="text-center mb-5">
          <div class="mistodo"></div>
        </div>
      </div>
    </div>
  </div>

<% end %>

<!--

-->

app/views/todo_items/_form.html.erb
<%= form_for([@todo_item.todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :completed_at %><br />
    <%= f.datetime_select :completed_at %>
  </div>
  <div class="field">
    <%= f.label :todo_list %><br />
    <%= f.text_field :todo_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing todo_item</h1>

<%= render 'form' %>

<%= link_to 'Show', [@todo_item.todo_list, @todo_item] %> |
<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_items/index.html.erb
<h1>Listing todo_items</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Completed</th>
    <th>Completed at</th>
    <th>Todo list</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.description %></td>
    <td><%= todo_item.completed %></td>
    <td><%= todo_item.completed_at %></td>
    <td><%= todo_item.todo_list %></td>
    <td><%= link_to 'Show', [todo_item.todo_list, todo_item] %></td>
    <td><%= link_to 'Edit', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item) %></td>
    <td><%= link_to 'Destroy', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo item', new_todo_list_todo_item_path(params[:todo_list_id]) %>

app/views/todo_items/new.html.erb
<h1>New todo_item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @todo_item.description %>
</p>

<p>
  <b>Completed:</b>
  <%= @todo_item.completed %>
</p>

<p>
  <b>Completed at:</b>
  <%= @todo_item.completed_at %>
</p>

<p>
  <b>Todo list:</b>
  <%= @todo_item.todo_list %>
</p>


<%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_item.todo_list, @todo_item) %> |
<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_lists/_form.html.erb
<%= form_with(model: @todo_list, local: true) do |form| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %></h2>

      <ul>
        <% @todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="input-group w-100 flex-column justify-content-center flex-nowrap mt-3 mb-3">
    <%= form.text_field :title, class: "form-control w-100", data: { reflex: 'change->TodoItem#form', id: current_user.id }, placeholder: 'Create new list' %>
    <%= form.hidden_field :user_id, :value => current_user.id %>

    <div class="input-group-append d-flex justify-content-center mt-2">
      <%= form.submit 'Add', class: "btn btn-success w-50" %>
    </div>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo List', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h5>
            <strong><%= @todo_list.title %></strong>
          </h5>
        </div>
        <%= form_for([@todo_list, @todo_item]) do |f| %>
          <div class="d-flex list-group-item">
            <div class="input-group">
              <%= f.text_field :description, class: 'form-control', placeholder: "Add new item" %>
            </div>
            <div class="input-group-append">
              <%= f.submit 'Add' %>
            </div>
          </div>
        <% end %>
        <div class="progress ml-4 mr-4 mt-4">
          <div class="progress-bar" role="progressbar" style="width: <%= @todo_list.percent_completed %>%" aria-valuenow="<%= @todo_list.percent_completed %>" aria-valuemin="0" aria-valuemax="100"><%= @todo_list.percent_completed %> %</div>
        </div>
        <ul class='card-body'>
          <% @todo_list.todo_items.each do |todo_item| %>
            <% if todo_item.completed? %>
              <li class='list-group-item'>
                <div class='d-flex justify-content-between aling-items-baseline'>
                  <span class="text-muted"style="text-decoration: line-through;">
                    <%= todo_item.description %>
                  </span>
                  <%= link_to '#', class: 'btn btn-info', data: { reflex: 'click->TodoItem#not_yet', id: todo_item.id } do %>
                    <i class="fas fa-times"></i>
                  <% end %>
                </div>
              </li> 
            <% else %>
              <li class='list-group-item'>
                <div class='d-flex justify-content-between aling-items-baseline'>
                  <span>
                    <%= todo_item.description %>
                  </span>
                  <%= link_to '#', class: 'btn btn-info', data: { reflex: 'click->TodoItem#all_good', id: todo_item.id } do %>
                    <i class="fas fa-check"></i>
                  <% end %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      

      <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
      <%= link_to 'Back', todo_lists_path %>
    </div>
  </div>
</div>